-- ============================================================
-- Extra LSP servers not covered by LazyVim language extras:
--   • sourcekit   — Swift / Objective-C / Objective-C++ (macOS only, requires Xcode)
--   • kotlin_language_server — Kotlin (Mason auto-installs)
--
-- Language split (avoids two servers fighting over the same buffer):
--   sourcekit → swift, objc, objcpp   (understands the Xcode build via buildServer.json)
--   clangd    → c, cpp                (pure C/C++; objc/objcpp removed from its defaults)
-- ============================================================

return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        -- Swift / Objective-C LSP.
        -- Requires: Xcode on macOS (sourcekit-lsp ships with the toolchain).
        -- For real symbol resolution in an Xcode project it also needs a
        -- buildServer.json at the project root (generated by xcode-build-server).
        -- NOTE: filetype names here are Neovim's (`objc`/`objcpp`). The LSP
        -- language IDs `objective-c`/`objective-cpp` are mapped automatically by
        -- lspconfig's sourcekit `get_language_id` — do not put them here.
        sourcekit = {
          filetypes = { "swift", "objc", "objcpp" },
        },

        -- C/C++ LSP. Drop objc/objcpp from clangd's defaults so sourcekit owns
        -- them (clangd's defaults are c/cpp/objc/objcpp/cuda/proto).
        clangd = {
          filetypes = { "c", "cpp", "cuda", "proto" },
        },

        -- Kotlin LSP. Mason auto-installs kotlin-language-server when present.
        kotlin_language_server = {},
      },
    },
  },

  -- Ensure Mason installs kotlin-language-server
  {
    "mason-org/mason.nvim",
    opts = function(_, opts)
      opts.ensure_installed = opts.ensure_installed or {}
      vim.list_extend(opts.ensure_installed, {
        "kotlin-language-server",
      })
    end,
  },
}
