return {
	"zaldih/themery.nvim",
	lazy = false,
	config = function()
		require("themery").setup({
			themes = {
				{ name = "blue", colorscheme = "blue" },
				{ name = "darkblue", colorscheme = "darkblue" },
				{ name = "default", colorscheme = "default" },
				{ name = "delek", colorscheme = "delek" },
				{ name = "desert", colorscheme = "desert" },
				{ name = "elflord", colorscheme = "elflord" },
				{ name = "evening", colorscheme = "evening" },
				{ name = "habamax", colorscheme = "habamax" },
				{ name = "industry", colorscheme = "industry" },
				{ name = "koehler", colorscheme = "koehler" },
				{ name = "lunaperche", colorscheme = "lunaperche" },
				{ name = "morning", colorscheme = "morning" },
				{ name = "murphy", colorscheme = "murphy" },
				{ name = "pablo", colorscheme = "pablo" },
				{ name = "peachpuff", colorscheme = "peachpuff" },
				{ name = "quiet", colorscheme = "quiet" },
				{ name = "retrobox", colorscheme = "retrobox" },
				{ name = "ron", colorscheme = "ron" },
				{ name = "shine", colorscheme = "shine" },
				{ name = "slate", colorscheme = "slate" },
				{ name = "sorbet", colorscheme = "sorbet" },
				{ name = "tokyonight", colorscheme = "tokyonight" },
				{ name = "tokyonight-day", colorscheme = "tokyonight-day" },
				{ name = "tokyonight-moon", colorscheme = "tokyonight-moon" },
				{ name = "tokyonight-night", colorscheme = "tokyonight-night" },
				{ name = "tokyonight-storm", colorscheme = "tokyonight-storm" },
				{ name = "torte", colorscheme = "torte" },
				{ name = "unokai", colorscheme = "unokai" },
				{ name = "vim", colorscheme = "vim" },
				{ name = "wildcharm", colorscheme = "wildcharm" },
				{ name = "zaibatsu", colorscheme = "zaibatsu" },
				{ name = "zellner", colorscheme = "zellner" },
				{ name = "sonokai", colorscheme = "sonokai" },
			},
			-- add the config here
		})
	end,
}
